### ISSUE TITLE
Compile error on mac OS 10.13 for wallet version 4.1

### ISSUE THREAD

**Issue by number435398** [TeslacoinFoundation/Teslacoin-v.4.0#20]
When following the instructions to compile on mac OS 10.13, I ran into the following error:

'as-iMac:src aa$ make -f makefile.osx
llvm-g++ -c -g -msse2 -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -fpermissive  -DMAC_OSX -DMSG_NOSIGNAL=0 -DBOOST_SPIRIT_THREADSAFE -DUSE_UPNP=1 -DUSE_IPV6=1 -DHAVE_BUILD_INFO -I"/Users/aa/Desktop/teslacoincore/src" -I"/Users/aa/Desktop/teslacoincore/src"/obj -I"/opt/local/include" -I"/opt/local/include/db48" -MMD -MF obj/alert.d -o obj/alert.o alert.cpp
In file included from alert.cpp:10:
In file included from /Users/aa/Desktop/teslacoincore/src/net.h:19:
/Users/aa/Desktop/teslacoincore/src/protocol.h:19:6: error: ISO C++ forbids
      forward references to 'enum' types
enum ServiceFlags : uint64_t {
     ^
/Users/aa/Desktop/teslacoincore/src/protocol.h:19:19: error: expected
      unqualified-id
enum ServiceFlags : uint64_t {
                  ^
/Users/aa/Desktop/teslacoincore/src/protocol.h:109:61: error: use of undeclared
      identifier 'NODE_NETWORK'; did you mean 'SER_NETWORK'?
        explicit CAddress(CService ipIn, uint64 nServicesIn=NODE_NETWORK);
                                                            ^~~~~~~~~~~~
                                                            SER_NETWORK
/Users/aa/Desktop/teslacoincore/src/serialize.h:50:5: note: 'SER_NETWORK'
      declared here
    SER_NETWORK         = (1 << 0),
    ^
3 errors generated.
make: *** [obj/alert.o] Error 1'

**Comment by Rastes10** [comment]
teslar

**Comment by Mstone87** [comment]
SER_NETWORK

**Comment by Mstone87** [comment]
Mstone assigned

**Comment by Mstone87** [comment]
Sugabitcoin

**Comment by Mstone87** [comment]
I accept

**Comment by Mstone87** [comment]
Sugar
